### PR TITLE
OSM v1 release code

### PR DESCRIPTION
**Pull request by Alexdavv**

### CODE REVIEW

**Comment by cgreich** [comment]
Where can I see the data in dev?

**Comment by Alexdavv** [comment]
In dev_osm schema

**Comment by pavgra** [comment]
What about polygons for the areas? Will there be a coupled CSV / any other data file with `concept_id` / `concept code` and `geom` pairs?

**Comment by Alexdavv** [comment]
> What about polygons for the areas? Will there be a coupled CSV / any other data file with `concept_id` / `concept code` and `geom` pairs?

@pavgra Sure, concept_code + geometry is already in the used source and csv may be exported now. Once release is done the concept_id + geometry pairs will be available as well.

**Comment by pavgra** [comment]
The reason I'm asking:
- I do not see where `geom` field is persisted into resulting (stage?) table
- not sure how that would be processed via Athena, we haven't discussed any solutions yet

**Comment by Alexdavv** [comment]
> * I do not see where `geom` field is persisted into resulting (stage?) table
It's non needed there now since CDM is not ready for storing the `geom` data.

> * not sure how that would be processed via Athena, we haven't discussed any solutions yet
Ok, good. We ready to discuss with Athena developers.

**Comment by pavgra** [comment]
> It's non needed there now since CDM is not ready for storing the geom data.

From what I recap (https://github.com/OHDSI/CommonDataModel/issues/220#issuecomment-436487997), it was decided not to store any binary data (polygons) in CDM. Plus, the data is required for separate apps / ETL, not for the CDM itself (the CDM itself will contain precomputed links and relations of entities from medical to geo domains). Therefore, not sure what you are waiting for.

**Comment by cgreich** [comment]
Not sure what you guys are debating. Now that we have the hierarchy of geographical concepts, we can assign to each a set of polygon information. Whether that's distributed through Athena or not is a different question. Looks like they are already available, so I would start with those. If Athena were to deliver them we'd have to go through the CDM WG ratification process and create new tables.

**Comment by pavgra** [comment]
@cgreich , how do I get polygon for a concept set from the vocabulary introduced by the PR?

**Comment by cgreich** [comment]
Right now informally. The team will publish them as a CSV file somewhere on the OHDSI website or here.

**Comment by pavgra** [comment]
Great. And this will be repeated for each release? (manual publishing of the CSV)

**Comment by cgreich** [comment]
Correct, until we add it to the CDM.

**Comment by Alexdavv** [comment]
> Right now informally. The team will publish them as a CSV file somewhere on the OHDSI website or here.

@cgreich @pavgra. Done and available [here](ftp://ftp.ohdsi.org/geography/geometry.csv).
DDL:
```
CREATE TABLE geometry
(	concept_id int,
	geom devv5.geometry(MultiPolygon,4326)
);
```

**Pull request merged**
