### PR TITLE
New ppi 6/17/2020

### PR DESCRIPTION
**Pull request by Yevhenii-Bezeha**
Added new concept_class_id, new relationship_id, changed generic_update ( 0 for PPI now).

### CODE REVIEW

**Comment by Alexdavv** [comment]
Guys, @dimshitc  @Yevhenii-Bezeha 
Why do we keep creating vocabulary-specific relationships if we're getting rid of them?

**Comment by dimshitc** [comment]
Good question.
I agree that there is not much sense in these vocabulary
specific relationships.
But this wasn't ratified officially yet.
@Christian Reich <reich@ohdsi.org>
Do you agree not to put vocabulary names in relationship_name?

In PPI we are going to create the  'Has question source (PPI)'
relationship, for example.

**Comment by Alexdavv** [comment]
> 'Has question source (PPI)'

That might be used in UKBiobank vocabulary, for example.

**Comment by Yevhenii-Bezeha** [comment]
Updated generic_update (set 1 for PPi as before).
Updated manual_changes (deleted PPI from the name of relationship_id -has question_source).
Updated load_stage for PPI (As base I used the last version of the load_stage from https://bitbucket.org/sciforce_odysseus/ppi/src/master/load_stage_2019_3%20(new%20logic).sql ).

**Pull request closed without merging**
