### PR TITLE
dmd changes

### PR DESCRIPTION
**Pull request by dimshitc**

### CODE REVIEW

**Comment by dimshitc** [comment]
I taken the latest branch of dmd for pull request, probably that's the one that was used for the latest dmd update

**Comment by Alexdavv** [comment]
@TinyRickC137 Do we consider this in the current dmd development?

**Comment by ekorchmar** [comment]
@TinyRickC137 @Alexdavv seems like the most changes narrow down to this code https://github.com/OHDSI/Vocabulary-v5.0/blob/313094ace4d2fb363f821cd253989ae7674925b5/dmd/postprocessing.sql#L169

**Comment by TinyRickC137** [comment]
@ekorchmar thank you very much, very helpful comment
@Alexdavv yes

**Pull request closed without merging**
