### PR TITLE
Icdo3

### PR DESCRIPTION
**Pull request by ekorchmar**
Still todo, in order:

1. Check examples of each concept_class_id for new relationships
2. Review replacement table provided by SNOMED; possibly use their instead
3. Review 1000 top by count concepts and their relations
4. Update documentation on wiki
Next update:
5. Update snomed_target_prepared to use original SNOMED RF2 files as source.

### CODE REVIEW

**Comment by ekorchmar** [comment]
1. Done
2. We have same replacements from same sources: no action needed
3. Lookup table dev_icdo3.check_me created.

**Comment by ekorchmar** [comment]
TODO:
Include concept_relationship_manual for manual Maps to to SNOMED.

Despite neoplasms hierarchy in SNOMED being very organised and mostly having correct attributes, and same concepts in ICDO3 being fully defined by default, some mappings fail to match. This occurs when SNOMED provides more granular attributes than ICDO allows or includes other details.

Ex.:
302826002 | Adrenal cortical adenoma (disorder)
    409703003 |Adrenal cortical adenoma - category (morphologic abnormality)
    68594002 |Adrenal cortex structure (body structure)

!= 8370/0-C74.9 | Adrenal cortical adenoma, NOS, of adrenal gland, NOS -- No way to specify adrenal gland cortex in ICDO

254632001 |Small cell carcinoma of lung (disorder)
   74364000 |Small cell carcinoma (morphologic abnormality)
   113255004 |Structure of parenchyma of lung (body structure)
!= 8041/3-C34.9 | Small cell carcinoma, NOS, of lung, NOS

While concepts usually end up in same hierarchhy branches and likely do not cause problems for end users, it still causes duplication of standard concepts which needs to be adressed.

Proposed solution:
1. Introduce CONCEPT_RELATIONSHIP_MANUAL with 'Maps to' relations between SNOMED and ICDO condition
2. Check every time if current logic affects concepts that receive mappings in normal way. Script should not go through if this happens.
3. (Low priority) Add mappings to topographies from ICDO histologies where possible; requires excessive testing to all r_to_c_all process.

**Comment by cgreich** [comment]
@ekorchmar:

I thought we deduped when we put them in? So, the ICDO SCCL only gets to be a standard if there is no SNOMED. Otherwise it's mapped. Did that not happen?

**Comment by ekorchmar** [comment]
Deduplication did happen in absolute most cases. It did not happen in cases when:
A. SNOMED provides more granular attributes than ICDO3 allows for;
B. SNOMED concept contains granular attributes besides morphology and topography (e.g. having "hereditary" as a separate property);
C. SNOMED concept is not designated as Defined for some reason. Each SNOMED release number of such concepts will diminish.
Number of concepts with those properties is low enough to manage them in manual table until we come up with a more elegant solution, e.g. individual rules for particular ICDO chapters.

**Comment by cgreich** [comment]
Got it.

**Comment by ekorchmar** [comment]
Still changes are required:
1. Allow Lymphoma-like disorders to be mapped to concept without topographhy if topography is generic Hematopoietic system.
2. Remove mapping to any topography from "Soft tissues"
3. Check if Standard concepts inherit attributes correctly

**Comment by ekorchmar** [comment]
1. Done
2. Done
3. They did not; Fixed

**Review by hardhouse — CHANGES_REQUESTED** [review]
1. need to put all *.csv on gdrive and fix the readme accordingly
2. https://github.com/OHDSI/Vocabulary-v5.0/blob/a2152410bf6b13ce6417ffd208fe8ea8c94a2d50/ICDO3/load_stage.sql#L12 missing other stage tables (you have to put them even if you don't use them)
3. https://github.com/OHDSI/Vocabulary-v5.0/blob/a2152410bf6b13ce6417ffd208fe8ea8c94a2d50/ICDO3/load_stage.sql#L827 this is an extra step
4. https://github.com/OHDSI/Vocabulary-v5.0/blob/a2152410bf6b13ce6417ffd208fe8ea8c94a2d50/ICDO3/load_stage.sql#L27 and https://github.com/OHDSI/Vocabulary-v5.0/blob/a2152410bf6b13ce6417ffd208fe8ea8c94a2d50/ICDO3/load_stage.sql#L434 - why "cascade"?
5. https://github.com/OHDSI/Vocabulary-v5.0/blob/a2152410bf6b13ce6417ffd208fe8ea8c94a2d50/ICDO3/load_stage.sql#L349 union all
6. https://github.com/OHDSI/Vocabulary-v5.0/blob/a2152410bf6b13ce6417ffd208fe8ea8c94a2d50/ICDO3/load_stage.sql#L794 not like '%.8'
7. https://github.com/OHDSI/Vocabulary-v5.0/blob/a2152410bf6b13ce6417ffd208fe8ea8c94a2d50/ICDO3/load_stage.sql#L1008 and https://github.com/OHDSI/Vocabulary-v5.0/blob/a2152410bf6b13ce6417ffd208fe8ea8c94a2d50/ICDO3/load_stage.sql#L1009 like '%.%' and not like '%.%'
8. https://github.com/OHDSI/Vocabulary-v5.0/blob/a2152410bf6b13ce6417ffd208fe8ea8c94a2d50/ICDO3/load_stage.sql#L347 same
9. https://github.com/OHDSI/Vocabulary-v5.0/blob/a2152410bf6b13ce6417ffd208fe8ea8c94a2d50/ICDO3/load_stage.sql#L1415 no longer needed step (https://forums.ohdsi.org/t/concept-synonym-usage-in-concept-searching/11562/8)
10. all dates must be in yyyymmdd format, not dd.mm.yyyy

**Comment by ekorchmar** [comment]
What needed now:
1. Check if all CSV files on gdrive
2. Test hierarchy modifications (if \d{4}\\3 maps to a morphology, treat this morphology as descendant of primary malignant neoplasm)
3. Check if concept_synonym is created in adherence to current convention

**Review by hardhouse — APPROVED** [review]

**Review by dimshitc — APPROVED** [review]

**Pull request merged**
