### PR TITLE
added MINs from rxnconso (https://github.com/OHDSI/Vocabulary-v5.0/is…

### PR DESCRIPTION
**Pull request by hardhouse**
…sues/632)

### CODE REVIEW

**Comment by mik-ohdsi** [comment]
I have asked @Alexdavv to review one more thing I am not sure is okay: if there would be new RxE entries that are duplicates to existing ones...

**Comment by hardhouse** [comment]
so what do we do then?

**Comment by cgreich** [comment]
Don't forget the links to ingredients and drug forms. What do you do with the drug components? They are always single.

**Comment by mik-ohdsi** [comment]
> I have asked @Alexdavv to review one more thing I am not sure is okay: if there would be new RxE entries that are duplicates to existing ones...

the above comment was not meant to go here but into the Investigational Drugs... but @cgreich is right about the links. The ones to the ingredients are looking good. Drug forms / components I haven't checked. I though MINs lead a somewhat solitary life for now and have been added, but are not completely integrated into the full hierarchy (kind of work in progress but wasn't tackled as it seemed to be too difficult?)

**Comment by cgreich** [comment]
Where can we check it?

**Comment by mik-ohdsi** [comment]
> Where can we check it?
@cgreich 
see that little awkward query above, it should provide you with some insight.

**Comment by cgreich** [comment]
But where is that? DevV5?

**Review by Alexdavv — APPROVED** [review]
The only erroneous diff is the following concept. Added to the booboo list

19051528	219329	Potassium Chloride-Potassium Gluconate	Ingredient	Non-standard	Invalid	Drug	RxNorm

**Wrong concept_class. Has to be a MIN**

**Pull request merged**
