### PR TITLE
Update input dosage's table - DS_STAGE, to roung all dosage values to…

### PR DESCRIPTION
**Pull request by sanua**
… three significant digits, according to the "AVOF-2010: RxE dosage rounding"

### CODE REVIEW

**Comment by cgreich** [comment]
No, that's dangerous. Here is why: The ds_stage contains data as numerator/denominator. The original drug was quantity factor * numerator/1. If we round the numerator, we can't turn it back without having to round again, and the multiple rounding will screw us up.

What we should do is to decide which one is the master representation, and round only during the script where necessary. 

Makes sense?

**Comment by dimshitc** [comment]
We will round then only 1 time after that.
As for me it's the best place for rounding (before we make unique_ds) - without that we'll make several components from the same dosage values (difference 0.1%) 
BTW it's seems to be good to apply the rule of 0.95 - 1.05 difference here to avoid getting of close dosages as different components (need to check if we have this within one vocabulary)
@aostropolets, can you please check this?

**Comment by aostropolets** [comment]
Anyway we need to round one more time - after extracting Quant factor.
As it is now, we use div just as you said: 5% and it seems to be better than 10%.

**Comment by sanua** [comment]
I was added rounding of values to EXTENSION_DS table. Is it safe to made rounding in that place ?

**Pull request closed without merging**
