### PR TITLE
Create small_cleanup

### PR DESCRIPTION
**Pull request by aostropolets**

### CODE REVIEW

**Comment by aostropolets** [comment]
> So, here you detect all concepts, that after RxNorm update, have RxNorm equivalents, right?
> 
> -- 5 Deprecate old relationships
> -- Why not to update depracate 'Source - RxNorm eq','Maps to' relationships?
> 
> -- 7 Add new replacements
> --why not to make the same replacements for 'RxNorm - Source eq','Mapped from' as well?

Adressed

**Comment by hardhouse** [comment]
https://github.com/OHDSI/Vocabulary-v5.0/blob/master/working/packages/vocabulary_pack/RxECleanUP.sql

**Comment by cgreich** [comment]
Is this somewhere documented? What is its purpose? What happened to the unmerged commits?

**Comment by aostropolets** [comment]
The commit is not merged as an embedded procedure was created instead:
https://github.com/OHDSI/Vocabulary-v5.0/blob/d6e343b7ba45b8fefabb5b59eef5ce60f0d5530b/RxNorm/load_stage.sql#L1205
and is an operational script, for which we currently don't have any separate documentation, similarly to other scripts like generic_update or concept_ancestor.
The purpose is to clean RxNorm - RxE duplicates after each script.

**Pull request closed without merging**
