### PR TITLE
Drug input qa

### PR DESCRIPTION
**Pull request by Alexdavv**

### CODE REVIEW

**Comment by aostropolets** [comment]
@Alexdavv  @ekorchmar  What is it and why do we need a separate file instead of existing QA?

**Comment by Alexdavv** [comment]
> @Alexdavv @ekorchmar What is it and why do we need a separate file instead of existing QA?

Revised and new checks split by 2 lists. It should not be a separate file. It should replace an existing one.
@ekorchmar @Tsemharb please confirm that no one check were lost

**Comment by Alexdavv** [comment]
BTW, @dimshitc @hardhouse we planned an integration with generic. That is why they’re separate.

**Comment by aostropolets** [comment]
I can't really check what's done because you created a new file. Could you, @ekorchmar, please describe how it should be integrated? And you, @Tsemharb, describe why you made the changes to QA? That would help me a lot

**Comment by ekorchmar** [comment]
Two files are created to separate Warnings (soft errors that may be harmless and don't break anything) from true Errors that would interrupt Build_RxE.

"Errors" file could be integrated as a function call in boiler to interrupt it if non-empty result is returned.

Personally I would prefer for them to be unified (with a new field added that shows level of error) and wrapped in a function that can be run manually or, again, integrated into Build_RxE to stop it from running if any Errors are encountered.

**Comment by Tsemharb** [comment]
I've added a few minor corrections for several cases. For example passing `1` as the first parameter to `coalesce` function. And I also rewrote 'multiple VOCABULARY_ID in drug_concept_stage' check because previous one took ten and a half minutes to run out of under twelve minutes of the whole QA script runtime.

**Comment by Alexdavv** [comment]
@dimshitc @hardhouse 
Let's just put it into master at this point so that everyone can use both QAs (old ones and integratable ones).

**Pull request merged**
